/* ------------------------------------------------------------------ *
 * Central configuration: models, the investment framework (weights
 * & decision thresholds), and tuning knobs. Documented in the README.
 * ------------------------------------------------------------------ */

export const MODELS = {
  // Env-overridable so the app keeps working if Groq renames/deprecates a model.
  reasoning: process.env.GROQ_MODEL_REASONING || "llama-3.3-70b-versatile",
  fast: process.env.GROQ_MODEL_FAST || "llama-3.1-8b-instant",
};

export const DIMENSIONS = [
  "business",
  "financials",
  "valuation",
  "growth",
  "moat",
  "risk",
] as const;
export type Dimension = (typeof DIMENSIONS)[number];

export const DIMENSION_LABELS: Record<Dimension, string> = {
  business: "Business Quality",
  financials: "Financial Health",
  valuation: "Valuation",
  growth: "Growth",
  moat: "Competitive Moat",
  risk: "Risk Profile",
};

/**
 * Weighted scorecard. Each dimension is scored 0-100 where higher is
 * always "more attractive" (risk is scored as quality / safety, so a
 * safer company scores higher). Weights sum to 1.0.
 *
 * Rationale (documented in README): valuation + financials + business
 * quality carry the most weight because they are the most objective and
 * most predictive of long-term outcomes; risk is weighted heavily too
 * because a single fatal flaw can wipe out an otherwise good thesis.
 */
export const WEIGHTS: Record<Dimension, number> = {
  business: 0.18,
  financials: 0.2,
  valuation: 0.18,
  growth: 0.14,
  moat: 0.12,
  risk: 0.18,
};

/** Decision thresholds on the weighted overall score (0-100). */
export const DECISION = {
  INVEST_FLOOR: 70,
  WATCH_FLOOR: 55,
} as const;

/** If the risk dimension is below this, downgrade the decision one tier. */
export const RISK_DOWNGRADE_FLOOR = 35;

/** Bounded agent limits. */
export const RESEARCH_MAX_TOOL_CALLS = 3;
export const ANALYST_CONCURRENCY = 2;

export const DISCLAIMER =
  "This report is generated by an autonomous AI research agent for educational and informational purposes only. " +
  "It is not investment, financial, legal, or tax advice. Figures are pulled live from third-party providers and " +
  "may be delayed or inaccurate. Always verify against primary sources and consult a licensed professional before investing.";
